// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "eyeSPY",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "eyeSPY",
            targets: ["AppModule"],
            bundleIdentifier: "NoahV.eyeSPY",
            teamIdentifier: "48GQ2C7SWV",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .binoculars),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To Locate Objects for the Eye Spy Game"),
                .speechRecognition(purposeString: "Used for an emotional check after using Eye Spy "),
                .microphone(purposeString: "Used for an emotional check after using Eye Spy ")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)